spring.application.name=ai-incident-resolver
spring.datasource.url=jdbc:postgresql://localhost:5432/incidentdb
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect